version: 0.0
os: linux

files:
  - source: .
    destination: /home/ec2-user/deployment-temp

hooks:
  AfterInstall:
    - location: install.sh
      timeout: 300
      runas: ec2-user

  ApplicationStart:
    - location: start.sh
      timeout: 300
      runas: ec2-user
