version: 0.0
os: linux

files:
  - source: frontend
    destination: /home/ec2-user/frontend
  - source: scripts
    destination: /home/ec2-user/scripts

hooks:
  AfterInstall:
    - location: scripts/install.sh
      timeout: 300
      runas: ec2-user

  ApplicationStart:
    - location: scripts/start.sh
      timeout: 300
      runas: ec2-user
