version: 0.0
os: linux

files:
  - source: /
    destination: /home/ec2-user/frontend
    overwrite: yes

hooks:
  AfterInstall:
    - location: scripts/install.sh
      runas: ec2-user
  ApplicationStart:
    - location: scripts/start.sh
      runas: root
