version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - cd frontend
      - npm install
  build:
    commands:
      - npm run build
      - mkdir -p output
      - cp -r dist output/
      - cp appspec.yml output/
      - cp -r scripts output/

artifacts:
  files:
    - '**/*'
  base-directory: frontend/output
