version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - echo Installing frontend...
      - cd frontend && npm install && npm run build && cd ..
      - echo Installing backend...
      - cd backend && npm install && cd ..
  build:
    commands:
      - echo Running tests...
      - cd backend && npm test || true
      - cd ../frontend && npm test --watchAll=false || true
  post_build:
    commands:
      - echo Zipping app for deployment...
      - zip -r artifact.zip frontend backend appspec.yml

artifacts:
  files:
    - artifact.zip
