version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Installing backend dependencies..."
      - cd backend
      - npm install

  build:
    commands:
      - echo "Backend build completed (if applicable)."

  post_build:
    commands:
      - echo "Preparing CodeDeploy artifact..."
      - cd ..
      - mkdir -p output
      - cp -r backend/* output/
      - cp backend/appspec.yml output/
      - cp -r backend/scripts output/

artifacts:
  files:
    - '**/*'
  base-directory: output
  discard-paths: no
