version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - echo Installing dependencies...
      - cd frontend && npm install && cd ..
      - cd backend && npm install && cd ..
  build:
    commands:
      - echo Running tests...
      - echo (Add unit test command here if available)
      - echo Build complete.
  post_build:
    commands:
      - echo Zipping app for deployment...
      - zip -r artifact.zip frontend backend appspec.yml scripts
artifacts:
  files:
    - artifact.zip
