version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/backend

hooks:
  BeforeInstall:
    - location: scripts/cleanup.sh
      timeout: 300
      runas: ec2-user

  AfterInstall:
    - location: scripts/install.sh
      timeout: 300
      runas: ec2-user

  ApplicationStart:
    - location: scripts/start.sh
      timeout: 300
      runas: ec2-user
