version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - cd backend
      - npm install

  post_build:
    commands:
      - cd backend
      - echo "⚙️ Preparing backend CodeDeploy artifact..."
      - mkdir -p output
      - shopt -s extglob  # Enable pattern matching
      - cp -r !(output) output/
      - cp appspec.yml output/
      - cp -r scripts output/

artifacts:
  files:
    - '**/*'
  base-directory: backend/output
