version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - cd backend
      - npm install
      - cd ..

  post_build:
    commands:
      - echo "⚙️ Preparing backend CodeDeploy artifact..."
      - mkdir -p backend-output
      - cp -r backend/* backend-output/
      - cp backend/appspec.yml backend-output/
      - cp -r backend/scripts backend-output/

artifacts:
  files:
    - '**/*'
  base-directory: backend-output
  discard-paths: no
